### ISSUE TITLE
Detect wifi login gateways

### ISSUE THREAD

**Issue by GoogleCodeExporter** [max99x/pagemon-chrome-ext#231]
```
When I'm using the wifi in the library or any other public place, I usually 
need to login before I can begin using the web. 

Those systems usually redirect every http request (if not logged in) to a 
special login page.

Problem is that page monitor thinks that the login page is an "updated version" 
of a monitored website and notifies on updates for all websites!

Maybe you should check that you have a real web access by maybe trying to 
access google.com or other resource that you know it should respond in a 
certain way. 

Great project. Really useful plugin. 
```

Original issue reported on code.google.com by `alex9...@gmail.com` on 15 Feb 2013 at 3:50

**Comment by GoogleCodeExporter** [comment]
Original comment by `max99x` on 16 Feb 2013 at 8:39
* Changed title: **Detect wifi login gateways**
* Changed state: **Accepted**
* Added labels: **Priority-Low**, **Type-Enhancement**
* Removed labels: **Priority-Medium**

**Comment by alex9913** [comment]
if pinging google is problematic, maybe it should just check that the page doesnt redirect to another domain.

**Comment by max99x** [comment]
It already pings Google to check that there's a connection, but doesn't verify that the result isn't a portal. Shouldn't be hard to remedy.

**Comment by alex9913** [comment]
Great. Sorry I dont know how this forking/pulling thing works. but here is the code adjustments I would propose to resolve this issue (not tested):

background.js:
line 13 add: 
var RELIABLE_CHECKPOINT_TITLE = 'Google';
line 276 subsitute with: 
if (xhr && xhr.status >= 200 && xhr.status < 300 && $(xhr).filter('title').text() == RELIABLE_CHECKPOINT_TITLE) {

Thanks again for your great plugin!

**Comment by alex9913** [comment]
After checking it further, there is a problem to get the title (or content) of the page because of the "same origin policy" (cross domain requests are not allowed). So the above code wont work, not even with .responseText (because it will always be empty)

**Comment by max99x** [comment]
Thanks for the patch! My concern is that even though it addresses this specific problem, if it fails, monitoring completely breaks for all 200k users. We can't rely on Google, a third-party site, to keep their title or specific HTML code consistent. If they decide to add some seasonal flourish to the title, or change their HTML to have an extra space or some such, this risks being broken.

The correct solution here is to set up a network checkpoint that the maintainer of the extension (which is me, at this point) can control and guarantee that it will always return the same value. However, since this check is performed every few seconds by hundreds of thousands of users, I can't simply use any old server lying around and hope for the best.

A less ideal but acceptable solution is something like what you have, but less fragile. Maybe just check that "Google" appears somewhere on the page, rather than explicitly checking the title. That will have false positives (i.e. some gateways will have "Google" somewhere), but the failure mode there is a lot more acceptable than the complete breakage due to a false negative described above.

**Comment by alex9913** [comment]
I share your concerns, to be on the safe side, you can use the opposite approach and look for wifi signs on google page.
for example the words hotspot / wifi / access that should not appear on google.com. 
Of course it will not detect 100% of the gates, but it will never fail 200k users if google page will change.

**Comment by alex9913** [comment]
the regex function is already in place for extracting the title from the html, so just need to adjust it slightly to search for those keywords or google variants instead

**Comment by max99x** [comment]
I've committed a variation of your patch, going with the Google keywords approach. The wifi keywords approach isn't safe enough. It can explode if Google decides to e.g. announce wi-fi service (not so far fetched), or more likely, if some resource URL or JavaScript code on the page happens to include any of those words.
